# no longer used as Github Action cronjob updates secret every hour
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    YOUR-SECRET-HERE
