---
- name: RKE2 installer
  hosts: postgres
  serial: 1
  # ignore_errors: yes
  vars_files:
    - ../../vault/vault_vars.yml

  tasks:
    - name: Setting role
      include_role:
        name: database
        tasks_from: postgres-cluster