name: Deploy Angular to ECR

on:
  push:
    branches: [angularjs-docker]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: angularjs-docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portfolio-angularjs
          # IMAGE_TAG: portfolio_angularjs_release_image
          #           sed -i "s#^export const EXPRESSJS_URL =.*#export const EXPRESSJS_URL = '$(head -n 1 API-URL)'#" angularjs/portfolio/globals.ts
        run: |
          sed -i "s|EXPRESSJS_URL: .*|EXPRESSJS_URL: \"$(head -n 1 API-URL)\",|" angularjs/portfolio/globals.ts
          export IMAGE_TAG=$(date '+%Y.%m.%d.%N')
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f angularjs/Dockerfile.prod
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
